---
title: "#BlackLivesMatters : une déclaration commune de "Forwards" et "R-Ladies"
author: "R-Ladies Global Leadership Team"
date: "2020-06-06"
description: "#BlackLivesMatters : une déclaration commune de "Forwards" et "R-Ladies"
tags: 
- social-justice
categories:
- r-ladies
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

En tant qu'organisations dédiées à augmenter la diversité et
l'intégration de tous dans nos communautés, nous soutenons #BlackLivesMatter et rejoignons ceux qui demandent justice face à
l'oppression systémique. Le racisme omniprésent affecte négativement la participation
de personnes noires dans notre société. Les événements en cours aux États-Unis font écho à ce qui s'est produit et continue de se produire pour les personnes marginalisées (ou réduites à être des minorités) à travers le monde. 
rassemblons des ressources et prenons des mesures pour amplifier la
voix des personnes noires, indigènes et de couleur dans la communauté R
maintenant et dans le futur.

Aux membres de notre communauté qui souffrent actuellement, nous
sommes à vos côtés, nous entendons vos voix, mais nous savons que cela
ne suffit pas pour provoquer le changement dont nous avons
besoin. Le travail visant à briser les systèmes d'injustice est lent et difficile, et nous savons que certain·e·s d'entre vous portent un peu plus le fardeau que d'autres. Il n'y a pas de mots pour rendre ceci plus facile ou léger.

## Un message de Forwards :

Forwards reconnaît que les personnes noires sont souvent absentes ou
négligées dans les activités principales de la communauté R. Nous
reconnaissons que beaucoup sont déçus par le progrès lent ou l'absence
d'action apparente. À un moment où l'actualité nous rappelle que l'injustice raciale tire les gens vers le bas, c'est notre rôle de
créer un espace pour les personnes noires, indigènes et de couleur
afin de développer leurs talents en tant que programmeurs en R et leaders communautaires.

Nous travaillons à travers de petites actions, qui nous espérons ont un impact, telles que :

- Mettre en valeur le travail de personnes de groupes sous-représentés
et partager des informations sur des événements clés et des opportunités
sur [\@R_Forwards Twitter](https://twitter.com/r_forwards).

- Soutenir les organisateurs de la conference useR! ave le programme de bourses pour la diversité

- Recommander des personnes de groupes sous-représentés pour des rôles
tels que conférenciers, membres de comités, président de séances,
etc.

- Soutenir l'équipe organisatrice de [AfricaR](https://africa-r.org/).

- Atteindre un groupe diversifié avec nos ateliers pour les femmes et filles avec nos [ateliers pour femmes et
filles](https://forwards.github.io/blog/2019/09/22/workshops-for-women-and-girls/)
et ateliers dans des régions mal desservies (par exemple
[Cuba](https://forwards.github.io/blog/2018/07/07/havanar/), [le Sud de l'Afrique](https://forwards.github.io/blog/2020/05/25/southern-africa-project-2020/)).

Nous compernons qu'il y aurait beaucoup plus à faire pour soutenir et
permettre la représentation des personnes noires, indigènes et de couleur
et nous sommes engagés à faire notre part. Nous allons continuer à
développer des actions et des objectifs à long terme pour améliorer la
représentation intersectionelle dans notre groupe de travail et de
manière générale dans la communauté R.

## Un message de R-ladies :

Même si la mission de R-Ladies et d'améliorer la diversité de genre dans
la communauté R, nous considérons également les difficultés que les
personnes noires subissent, et l'effet de l'intersectionnalité lorsqu'un
membre s'identifie avec plusieurs groupes sous-représentés. R-ladies
Global s'engage à améliorer comment l'organisation soutient les
personnes noires, indigènes et de couleur au travers des actions suivantes :

- Nous allons débuter et continuer une discussion autour d'actions
concrètes pour promouvoir la justice sociale partout dans le monde à
l'aide de chaînes dans nos espaces Slack. Nous nous engageons à écouter,
faire preuve d'empathie et chercher à comprendre et transformer nos
discussions en action. Nous nous engageons à faire de nos communautés
des endroits non seulement sûrs pour tous nos membres, mais aussi
d'esapce de travail pour plus d'équité et de justice.

- Nous allons incorporer dans notre site web une page dédiée de
resources et d'informations pour les actions concrètes que nous, en tant
qu'organisation et en tant qu'individus nous pouvons faire pour soutenir #BlackLivesMatter et d'autres mouvements de justice sociale.

- Nous allons améliorer la représentation éthnique et raciale de
l'équipe organisatrice de R-ladies Global de telle sorte que toutes les
minorités intersectionnelles soient mieux représentées.

- Nous allons lancer des programmes pour soutenir nos membres (par
exemple par des bourses de voyages, des bons pour des livres, des
inscriptions pédagogiques) grâce aux resources financières données à
R-Ladies, nous allons donner 50% de ces financements à des membres avec
des identités intersectionnelles et la moitié de ces derniers sera
dirigée de manière exclusive au membres noirs.

## Déclaration finale

Nous allons travailler de manière plus intensive pour écouter et
amplifier les voix des membres de minorités dans nos communautés partout
dans le monde. Nous sommes investi dans le travail permanent de
déconstruire les systèmes d'injustices et faire de la place à celles et
ceux qui sont actuellement en train de souffrir à cause de ces systèmes
afin qu'ils puissent pleinement participer et occuper des postes à
responsabilité. Nous pressons chacun dans la communauté R à faire de même.

Équipe principale de Forwards : Heather Turner, Noa Tamir, Tatjana
Kecojevic, Emily Dodwell, Kevin O’Brien, Julie Josse.

Équipe de R-Ladies Global : Claudia Vitolo, Erin LeDell, Hannah Frick, Laura Ación, Athanasia Monika Mowinckel, Yanina Bellini Saibene, Noa Tamir, Maëlle Salmon, Jennifer Thompson, Florencia D’Andrea, Patricia A. Loto, Saranjeet Kaur Bhogal, Christin Zasada, Nadejda Sero, Sheila Saia. 

Organisatrices (actuelles et passées) d'antennes locales de R-Ladies et
autres fortement impliquées dans R-ladies et dans les communautés
R-ladies: gwynn sturdevant, Paola Corrales, Paloma Rojas-Saunero, Riva Quiroga, Roxana Noelia Villafañe, Monica L. Alonso, Danielle Navarro, Mine Çetinkaya-Rundel, Sara Mortara, Genelle Denzin, Divya Seernani, Elisa Schneider, Kyla McConnel, Ana Laura Diedrichs, Liza Dosso, Mariel Lovatto, María Nanton, Ludmila Janda, Hazel Kavili, Ines Teacã, Lucía Rodríguez Planes, Andrea Sánchez-Tapia, Disha Patil, Ayanthi Gunawardana, Jan Strappa, Kaelen Medeiros, Vebashini Naidoo, Emily Dodwell, Julia Silge, Marcela Alfaro, Jenny Bryan, Lucy D’Agostino McGowan, Alison Hill, Andrea Gómez Vargas, Angela Li, Beatriz Milz, Haydée Svab, Tijana Blagojev, Katarina Kosmina, Jovana Savic.
